### PR TITLE
Release 1.4.0

### PR DESCRIPTION
**Pull request by matteotrubini**
https://github.com/toughdeveloper/oc-imageresizer-plugin/blob/9515abc7aca8caa1455dfc4d00208e7df9991f48/updates/version.yaml#L15-L23

### CODE REVIEW

**Comment by matteotrubini** [comment]
`v1.4.0` branch contain only ce5fa210a1ac3002e3fe581df65bf7b566e2e63f, so it should be reviewed, code changes ported to develop and finally removed to avoid confusion.

@toughdeveloper @maartenmachiels @rejuvenatedigital please comment with 👍 or 👎

**Comment by maartenmachiels** [comment]
Looks good. Maybe mention in version.yaml that files that have spaces are now handled properly. I'll be testing out shortly.

**Comment by toughdeveloper** [comment]
@matteotrubini @maartenmachiels - Seems fine on the face of it to me, I'm not in a position to test. But as soon as its merged to master @ me and I'll push the update on October.

**Comment by matteotrubini** [comment]
@toughdeveloper `v1.4.0` renamed in `aws-s3` to complete the feature before merge it into develop.
Here we go!

**Comment by toughdeveloper** [comment]
Thanks everyone for changes on this. Glad to see the project being maintained again :)

**Pull request merged**
