### PR TITLE
Use original filename for cache key

### PR DESCRIPTION
**Pull request by lthurston**
See issue #52

### CODE REVIEW

**Comment by lthurston** [comment]
This is a pretty straight forward change. Let me know if you want to see any modifications.

**Comment by lthurston** [comment]
@toughdeveloper Is this project being managed anymore?

**Comment by maartenmachiels** [comment]
I haven't seen a response from @toughdeveloper in months. I'm not feeling very confident about this. Maybe someone should fork the project, so we can get on with it?

**Comment by lthurston** [comment]
Yeah, it would be pretty ridiculous for us all to maintain our own forks. I can start a new issue and mention everyone who has an open PR to see who would be willing to take this on. I would be willing to manage the fork, but can't promise I'll always have enough time to deal with it.

**Comment by toughdeveloper** [comment]
@lthurston @maartenmachiels  - Hi, Sorry for not responding sooner. I don't have time to maintain this anymore. 

Feel free to fork, I will update the readme to point to a maintained version.

**Comment by lthurston** [comment]
Thanks, @toughdeveloper, for letting us know and also for this useful plugin.

**Comment by lthurston** [comment]
See #55 for further discussion of project maintenance.

**Comment by matteotrubini** [comment]
I think that this enhancement will have high priority given the SEO best practices.

@lthurston this PR seems to be incomplete, maybe some commit are missing?

@maartenmachiels did you have check this PR before?

**Comment by maartenmachiels** [comment]
Hi matteo, no I didn't check this before...

**Comment by lthurston** [comment]
Sorry @matteotrubini , little behind on email. This PR is complete and running in production environments (saving GB of disk space). It's a simple change that just uses the relative path to an original images rather than the complete path in generating the cache key.

**Review by matteotrubini — COMMENTED** [review]
Can you explain how changes let's us to use original's relative path please?

**Comment by matteotrubini** [comment]
@lthurston please also rebase your commit on top of current `develop`, thank you!

**Comment by lthurston** [comment]
Actually, yeah, you're right. Something seems to be missing. I'll figure out what it is.

**Comment by lthurston** [comment]
@matteotrubini I've finally pushed the right changes. Sorry about the delay.

**Comment by lthurston** [comment]
Hi @matteotrubini, I'm just checking in and hoping this simple change can get merged in.

**Comment by lthurston** [comment]
Does anyone on this thread have a moment to +1 this? I'm anxious to getting it merged in because as mentioned in #52, all images get regenerated using our deploy setup (Capistrano deploys new releases to a uniquely named folder each time, then creates a symlink). We've got Composer configured to use our fork of this, but it'd be great to wrap this up.

**Review by chocolata — APPROVED** [review]

**Comment by chocolata** [comment]
I just reviewed it - looks good to me. Do we have everything to proceed now? I'm also a big fan of keeping the original filenames. SEO-wise it's a great idea to keep those names descriptive.

**Comment by lthurston** [comment]
Thanks @maartenmachiels. @matteotrubini Any chance you can merge this bad boy in?

**Comment by chocolata** [comment]
@matteotrubini could you kindly do this?

**Comment by chocolata** [comment]
Thank you Matteo.

**Pull request merged**
