### PR TITLE
Remove temporary file after resizing it

### LINKED ISSUE #45: Temporary file is not deleted
I have the following file in my `media` folder:

```
-rw-rw-r-- 1 user user 4120619 Dec  4 09:05 images/IMG_0281.JPG
```

So I put the following in one of my views to use this image:

```
    <img src="{{ 'images/IMG_0281.JPG'|media|resize(600,600) }}">
```

This creates (in my case) the following directory tree in the `uploads/public` directory:

```
73f
└── [       4096]  fe6
    └── [       4096]  021
        ├── [    4120619]  73ffe6021b91d705a567bed46a2d7871
        └── [     107565]  thumb__600_600_0_0_auto.JPG
```

However as you notice here, the file `73ffe6021b91d705a567bed46a2d7871` is actually just the image (verified with md5sum). This needlessly doubles the storage space for the original full-size image. Instead **only** the thumbnail should be stored and the original image should be only in the original directory.

### PR DESCRIPTION
**Pull request by multiwebinc**
Fixes #45

### CODE REVIEW

**Comment by lthurston** [comment]
See #55 for discussion of future maintenance of this project.

**Comment by maartenmachiels** [comment]
Just tested this out, this works like a charm!

**Comment by matteotrubini** [comment]
@maartenmachiels please remember to merge PR on develop branch as agreed with @toughdeveloper See https://github.com/toughdeveloper/oc-imageresizer-plugin/issues/55#issuecomment-483201331

**Comment by maartenmachiels** [comment]
Hi Matteo, I'm sorry for this. My mistake. I've reverted the changes. Could you kindly merge https://github.com/toughdeveloper/oc-imageresizer-plugin/commit/ea790a3b42df32b9963d7a2ef8c82f9c472a8c74 into develop?

**Comment by matteotrubini** [comment]
Already done (manually) via 3a840fceab0a815e5bc038701a2d2de5ac2d05ac

**Pull request merged**
