### PR TITLE
Update the Hungarian translation

### PR DESCRIPTION
**Pull request by gergo85**

### CODE REVIEW

**Comment by toughdeveloper** [comment]
@gergo85 - Thanks again. Can I ask one more favour please. Could you provide a translation to the tinyPng API key validation error message (https://github.com/toughdeveloper/oc-imageresizer-plugin/blob/master/models/Settings.php#L19)

When I built in this validation I was unsure on how to translate this, although have since seen translations used in the Static Page plugin on validation. 

Thanks!

**Comment by gergo85** [comment]
Try this:
```
public $customMessages = [
     'valid_tinypng_key' => Lang::get('toughdeveloper.imageresizer::lang.settings.valid_tinypng_key')
];
```

**Comment by toughdeveloper** [comment]
Sorry, I was asking for the Hungarian translation of "The tinypng key entered could not be validated, please check the key and try again.'"

Google translates as "A tinypng beírt kulcs nem lehetett érvényesíteni, ellenőrizze a gombot, és próbálja újra." Although I assume this could be improved. 

Thanks

**Comment by gergo85** [comment]
"A megadott tinypng kulcsot nem lehet érvényesíteni. Kérjük ellenőrizze és próbálja újra."

**Pull request merged**
